### ISSUE TITLE
How to download the dataset and process video files?

### ISSUE THREAD

**Issue by Weihong-Liu** [sabrikhalil/Micro_Mobility_Detection#2]
Hi,

I couldn't find the annotations_train_yolo.json and other files in the drive. Could you please provide guidance on how to download the dataset?

Additionally, how should the video files in the drive be processed into images?

Thank you!

**Comment by Weihong-Liu** [comment]
I encountered a dimension mismatch error when using the `imagenet_vid_fgfa_style.py` script with the ImageNet dataset. Below is the traceback:

```
Traceback (most recent call last):
  File "tools/train.py", line 219, in <module>
    main()
  File "tools/train.py", line 208, in main
    train_model(
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmtrack/apis/train.py", line 179, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmtrack/models/vid/base.py", line 265, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmtrack/models/vid/base.py", line 189, in forward
    return self.forward_train(
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmtrack/models/vid/dff.py", line 148, in forward_train
    ref_x = self.detector.extract_feat(ref_img[:, 0])
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmdetection/mmdet/models/detectors/single_stage.py", line 45, in extract_feat
    x = self.neck(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/Micro_Mobility_Detection/src/mmtracking/mmdetection/mmdet/models/necks/yolox_pafpn.py", line 139, in forward
    torch.cat([upsample_feat, feat_low], 1))
RuntimeError: Sizes of tensors must match except in dimension 3. Got 63 and 64 (The offending index is 0)
```

Could you please provide guidance on how to resolve this issue?

Thank you!

**Comment by sabrikhalil** [comment]
**Hi,**

Thank you for your interest in our work!

#### Regarding the Missing Annotations:

The annotation files for the model (in the FGFA format) are available in the following path on the shared drive:  
**`Annotations/Annotations_fgfa_format`**

I have just added annotations for both **640x640** and **512x256** resolutions. These include annotations for both training and testing data. Please ensure you download the appropriate annotations that match your intended image resolution and architecture settings.

#### Regarding the Dataset and Frame Extraction:

The video files can be found in the following folders:  
- **Training videos:** `videos/videos_train`  
- **Testing videos:** `videos/videos_test`

To process the video files into images:  
1. Download the videos from the above directories.  
2. Use the code provided at the end of the notebook to extract frames. This script will process the videos and organize the frames in a structured format suitable for training.

#### Regarding the Dimension Mismatch Error:

From the traceback, it appears the issue may be caused by a mismatch between the image dimensions, annotation formats, and the expected input size of the architecture. To resolve this:  
1. Ensure the images and annotations are correctly paired and correspond to the same resolution (e.g., **640x640** or **512x256**).  
2. Check the model configuration input size, make sure it's the same.  

The code is functioning correctly for me with the provided dataset and annotations, so ensuring all formats align should resolve the error.

If you encounter any further issues, please feel free to reach out.  

Thank you!
